### ISSUE TITLE
Incompatibility with the biblatex "related entries" system?

### ISSUE THREAD

**Issue by russella** [moewew/biblatex-trad#24] opened 2015-01-05 02:07 UTC
Dear Marco,

Thanks again for all your work on the trad-* system. I've used it for several articles now.

I would like to to deploy trad-plain for all articles in the Journal "Theory of Computing," but I have run in to a snag. I would be really grateful for some advice. For Theory of Computing, I'll need to use the "related entries" system in order to refer to previous versions of an article. Consider the minimal example posted below.

1. If you typeset it as written, it works fine, showing the related entries for both articles.
2. If you comment out the \usepackage[*]{biblatex} line, and uncomment the following one, you will see that the system only shows the related entries for the /first/ entry.

What's going wrong?

Any help very, very appreciated!

Best, Alex

---------EXAMPLE CODE BELOW---------
\documentclass{article}
\usepackage[american]{babel}
\usepackage{csquotes}

%%%%% Try with each of the following lines uncommented!
\usepackage[backend=biber]{biblatex}
%\usepackage[backend=biber,bibstyle=trad-plain]{biblatex}
%%%%% End part to edit

\usepackage[colorlinks]{hyperref}

\renewcommand*{\relatedpunct}{\addcolon\space}
\renewcommand*{\relateddelim}{\addcomma\space}

\newbibmacro*{related:prelim}[1]{%
  \renewcommand*{\newunitpunct}{\addcomma\space}%
  \entrydata{#1}{\usebibmacro{doi+eprint+url}}}

\NewBibliographyString{prelim,prelims}
\DefineBibliographyStrings{american}{%
  prelim = {Preliminary version},
  prelims = {Preliminary versions}}

\begin{filecontents}{\jobname.bib}
@article{v008a021,
  author = {Roy Kasher and Julia Kempe},
  title = {Two-Source Extractors Secure Against Quantum Adversaries},
  year = {2012},
  pages = {461-486},
  doi = {10.4086/toc.2012.v008a021},
  journal = {Theory of Computing},
  volume = {8},
  related = {kasher/arxiv,kasher/approx},
  relatedtype = {prelim}}
@article{v008a021alt,
  author = {Roy Lasher and Julia Lempe},
  title = {Two-Source Extractors Secure Against Quantum Adversaries},
  year = {2012},
  pages = {461-486},
  doi = {10.4086/toc.2012.v008a021},
  journal = {Theory of Computing},
  volume = {8},
  related = {lasher/arxiv,lasher/approx},
  relatedtype = {prelim}}
@online{kasher/arxiv,
  author = {Kasher, Roy and Kempe, Julia},
  title = {Two-Source Extractors Secure Against Quantum Adversaries},
  eprinttype = {arxiv},
  eprintclass = {quant-ph},
  eprint = {1005.0512},
  month = may,
  year = {2010}}
@inproceedings{kasher/approx,
  author = {Kasher, Roy and Kempe, Julia},
  title = {Two-source extractors secure against quantum adversaries},
  booktitle = {Proceedings of the 13th international conference on Approximation,
    and the 14th International conference on Randomization, and combinatorial
    optimization: algorithms and techniques},
  series = {APPROX/RANDOM'10},
  year = {2010},
  pages = {656--669},
  url = {http://dl.acm.org/citation.cfm?id=1886521.1886572},
  publisher = {Springer-Verlag},
  location = {Berlin, Heidelberg}}
@online{lasher/arxiv,
  author = {Lasher, Roy and Lempe, Julia},
  title = {Two-Source Extractors Secure Against Quantum Adversaries},
  eprinttype = {arxiv},
  eprintclass = {quant-ph},
  eprint = {1005.0512.LA},
  month = may,
  year = {2010}}
@inproceedings{lasher/approx,
  author = {Lasher, Roy and Lempe, Julia},
  title = {Two-source extractors secure against quantum adversaries},
  booktitle = {Proceedings of the 13th international conference on Approximation,
    and the 14th International conference on Randomization, and combinatorial
    optimization: algorithms and techniques},
  series = {APPROX/RANDOM'10},
  year = {2010},
  pages = {656--669},
  url = {http://dl.acm.org/citation.cfm?id=LA1886521.1886572},
  publisher = {Springer-Verlag},
  location = {Berlin, Heidelberg}}
\end{filecontents}

\addbibresource{\jobname.bib}
\begin{document}
\cite{v008a021,v008a021alt}
\printbibliography
\end{document}

**Comment by moewew** [comment] 2015-09-09 13:58
It seems to me that a call to `\usebibmacro{related:init}%` is missing just before `\usebibmacro{related}%` in the drivers. It might not be a bad idea to also allow for the related feature to be toggled on and off as in `standard.bbx`:
```
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
```

**Comment by moewew** [comment] 2016-05-27 05:27
I have merged the pull request. If you could confirm that the issue is solved, we can close this issue.

**Comment by russella** [comment] 2016-05-27 22:56
Yes, this solves the issue!

**Comment by moewew** [comment] 2016-05-28 06:26
Brilliant!

**Closed by moewew** 2016-05-28 06:26 UTC
